﻿services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: bitesbyteapp:V2
    container_name: webapi
    ports:
      - "7000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1400;Database=BitesByteDB;User Id=sa;Password=Str0ngPamicrosoft/mssql-server-linux:2017-latestw0rd;Trusted_Connection=False;TrustServerCertificate=true
 